version: '2'

services:
    volume_log:
        image: busybox:latest
        volumes:
            - /var/log/nginx

    volume_cache:
        image: busybox:latest
        volumes:
            - /var/cache/nginx

    volume_data:
        image: busybox:latest
        volumes:
            - /var/lib/mysql

    mysql:
        image: mysql:latest
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: db
            MYSQL_PASSWORD: db
            MYSQL_DATABASE: database
        volumes_from:
            - volume_data

    php:
        build: ./php
        image: php
        expose:
            - "9000"
        links:
            - mysql:database
        volumes_from:
            - symfony
    
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php:php
        volumes_from:
            - volume_log
            - volume_cache
            - symfony

    symfony:
        build: ./symfony
        image: symfony
